sonar.projectKey=mouhamet-thiam_immosn
sonar.organization=mouhamet-thiam

sonar.sources=backend/src/main,frontend/src

sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**
