@baseUrl=http://localhost:8080/api/v1/types-bien

### Types de bien - Create
POST {{baseUrl}}
Content-Type: application/json
accept: application/json

{
    "libelle": "Appartement"
}

### Types de bien - List active
GET {{baseUrl}}
accept: application/json

### Types de bien - List paged
GET {{baseUrl}}/paged?page=0&size=10
accept: application/json

### Types de bien - Get by id
GET {{baseUrl}}/1
accept: application/json

### Types de bien - Update
PUT {{baseUrl}}/1
Content-Type: application/json
accept: application/json

{
    "id" : 1,
    "libelle": "Appartement rénové"
}

### Types de bien - Archive
DELETE {{baseUrl}}/1
accept: application/json
