FROM node:20 AS build

WORKDIR /app

COPY ../frontend/package*.json ./frontend/
WORKDIR /app/frontend
RUN npm install

COPY ../frontend ./
RUN npm run build


FROM nginx:alpine

COPY --from=build /app/frontend/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]