spring.application.name=backend

page.default.size=${PAGE_DEFAULT_SIZE:10}
page.admin.size=${PAGE_ADMIN_SIZE:20}

server.port=8080
spring.datasource.url=jdbc:h2:mem:apiv1db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console